import {
  pgTable,
  serial,
  integer,
  text,
  timestamp,
  index,
  uniqueIndex,
  check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { lessonsTable } from "./lessons";
import { lessonNodesTable } from "./lesson-nodes";

/**
 * Canonical lesson outcomes are the durable C1 curriculum layer.
 *
 * `lessons.lesson_outcomes` remains the legacy JSON compatibility field. These
 * rows intentionally do not replace or infer from it: a teacher must review
 * any deterministic backfill before it becomes meaningful curriculum data.
 */
export const lessonOutcomesTable = pgTable(
  "lesson_outcomes",
  {
    id: serial("id").primaryKey(),
    lessonId: integer("lesson_id")
      .notNull()
      .references(() => lessonsTable.id, { onDelete: "cascade" }),
    outcomeText: text("outcome_text").notNull(),
    sequence: integer("sequence").notNull(),
    // draft → reviewed → approved mirrors the existing MicroNode authoring lifecycle.
    status: text("status").notNull().default("draft"),
    // teacher_authored | legacy_backfill | mapping_import
    provenance: text("provenance").notNull().default("teacher_authored"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("lo_lesson_sequence_uidx").on(t.lessonId, t.sequence),
    index("lo_lesson_idx").on(t.lessonId),
    check("lo_status_chk", sql`${t.status} IN ('draft','reviewed','approved')`),
    check(
      "lo_provenance_chk",
      sql`${t.provenance} IN ('teacher_authored','legacy_backfill','mapping_import')`,
    ),
  ],
);

/**
 * A lesson outcome can be supported by many MicroNodes and a MicroNode can
 * contribute to many outcomes. `requiredCognitiveDepth` is a stable semantic
 * value, deliberately not a foreign key to a Cognitive Path row because those
 * rows can be regenerated by the authoring workflow.
 */
export const lessonOutcomeNodeAlignmentsTable = pgTable(
  "lesson_outcome_node_alignments",
  {
    id: serial("id").primaryKey(),
    // Explicit lesson scope permits fast, ownership-scoped reads. The API
    // validates it matches both referenced records before every write.
    lessonId: integer("lesson_id")
      .notNull()
      .references(() => lessonsTable.id, { onDelete: "cascade" }),
    lessonOutcomeId: integer("lesson_outcome_id")
      .notNull()
      .references(() => lessonOutcomesTable.id, { onDelete: "cascade" }),
    lessonNodeId: integer("lesson_node_id")
      .notNull()
      .references(() => lessonNodesTable.id, { onDelete: "cascade" }),
    role: text("role").notNull(),
    requiredCognitiveDepth: text("required_cognitive_depth").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("lona_outcome_node_uidx").on(t.lessonOutcomeId, t.lessonNodeId),
    index("lona_lesson_idx").on(t.lessonId),
    index("lona_node_idx").on(t.lessonNodeId),
    check("lona_role_chk", sql`${t.role} IN ('REQUIRED','SUPPORTING')`),
    check(
      "lona_depth_chk",
      sql`${t.requiredCognitiveDepth} IN ('remember','understand','apply','analyze','evaluate','create')`,
    ),
  ],
);

export const OUTCOME_ALIGNMENT_ROLES = ["REQUIRED", "SUPPORTING"] as const;
export type OutcomeAlignmentRole = (typeof OUTCOME_ALIGNMENT_ROLES)[number];

export const OUTCOME_STATUS_VALUES = ["draft", "reviewed", "approved"] as const;
export type OutcomeStatus = (typeof OUTCOME_STATUS_VALUES)[number];

export const insertLessonOutcomeSchema = createInsertSchema(lessonOutcomesTable, {
  outcomeText: z.string().trim().min(1),
  status: z.enum(OUTCOME_STATUS_VALUES).optional(),
}).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertLessonOutcome = z.infer<typeof insertLessonOutcomeSchema>;

export const insertLessonOutcomeNodeAlignmentSchema = createInsertSchema(
  lessonOutcomeNodeAlignmentsTable,
  {
    role: z.enum(OUTCOME_ALIGNMENT_ROLES),
    requiredCognitiveDepth: z.enum([
      "remember",
      "understand",
      "apply",
      "analyze",
      "evaluate",
      "create",
    ]),
  },
).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertLessonOutcomeNodeAlignment = z.infer<
  typeof insertLessonOutcomeNodeAlignmentSchema
>;